### ISSUE TITLE
/usr/bin/ld: cannot find -ldazzdb

### ISSUE THREAD

**Issue by mictadlo** [PacificBiosciences/DALIGNER#29]
Hi,
I downloaded the following missing source files into the Daligner folder:

```
wget -c https://raw.githubusercontent.com/PacificBiosciences/DAZZ_DB/master/DB.h
wget -c https://raw.githubusercontent.com/PacificBiosciences/DAZZ_DB/master/DB.c
wget -c https://raw.githubusercontent.com/PacificBiosciences/DAZZ_DB/master/QV.h
wget -c https://raw.githubusercontent.com/PacificBiosciences/DAZZ_DB/master/QV.c
```
but I got:
```
 make
cc -O3 -Wall -Wextra -fno-strict-aliasing -Wno-unused-result -I/lustre/work-lustre/waterhouse_team/apps/LA4Falcon/../DAZZ_DB -I/include  -c -o daligner.o daligner.c
cc -L/lustre/work-lustre/waterhouse_team/apps/LA4Falcon/../DAZZ_DB  daligner.o filter.o align.o  -ldazzdb -lm -lpthread -o daligner
/usr/bin/ld: cannot find -ldazzdb
/usr/bin/ld: skipping incompatible /usr/lib/../lib/libm.so when searching for -lm
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'daligner' failed
make: *** [daligner] Error 1
rm daligner.o
```
What did I miss?

Thank you in advance.

Michal

**Comment by pb-cdunn** [comment]
If you use the upstream http://github.com/thegenemyers/DALIGNER, you'll find it easier to build because Dr. Myers always *copies* the DAZZ_DB dependencies in repos which need it. At PacBio, we build DAZZ_DB first. When you use our repo, you're probably using our `GNUmakefile`, which is different than the original `Makefile`.

To build our repos, you can choose among these options:
* https://github.com/PacificBiosciences/FALCON-integrate/wiki/Installation
* https://github.com/PacificBiosciences/pitchfork/wiki
